In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
    print(e)

1
2
3


In [5]:
for e in A:
    print(e)

1
2
3


In [6]:
L.append(4)

In [7]:
L

[1, 2, 3, 4]

In [8]:
L + [5]

[1, 2, 3, 4, 5]

In [9]:
A + np.array([4])

array([5, 6, 7])

In [10]:
A + np.array([4,5,6])

array([5, 7, 9])

In [11]:
A + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [12]:
2 * A

array([2, 4, 6])

In [13]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L2 = []
for e in L:
    L2.append(e + 3)

In [16]:
L2

[4, 5, 6, 7]

In [17]:
L2 = [e + 3 for e in L]

In [18]:
L2

[4, 5, 6, 7]

In [19]:
L2 = []
for e in L:
    L2.append(e**2)
L2

[1, 4, 9, 16]

In [20]:
A**2

array([1, 4, 9])

In [21]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [22]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [23]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [24]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])